language: ruby
script: bundle exec rspec
rvm:
  - 2.3.1
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/activemodel_4.gemfile
  - gemfiles/activemodel_5.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/activemodel_5.gemfile
  deploy:
  provider: script
  script: sh bin/package_push.sh
  on:
    branch: RD-1545/use_gemfury
